### ISSUE TITLE
new Function('return this')() is eval == bad code

### ISSUE THREAD

**Issue by duzun** [lahmatiy/es6-promise-polyfill#3]
I'm considering using this library in a Firefox Addon, but because of the last line my addon will be rejected by Mozilla Addon reviewers, as it is using `eval`.

Is there a special reason for that ?

Why not `typeof global != 'undefined' ? global : this` ?

**Comment by lahmatiy** [comment]
Hm... It's really strange decision by Mozilla reviewers. `new Function('return this')()` is most compact and robust construction to get real "global".

> Why not

There is no guarantee that `this` points to global.

Anyway going to solve issue.

**Comment by duzun** [comment]
I'm not 100% sure they will reject exactly this context, they might accept it as an exception.
But according to documentation and automated validation tools, it is likely to be rejected, or at least would require a manual review...

There is no guarantee `this` points to global in all environments, but if you target only browsers and node.js `typeof global != 'undefined' ? global : this` is enough.

I susspect there might be issues with build tools like WebPack, but not sure.
